name: CI

env:
  OSS_CAD_SUITE: '2026-07-24'

on:
  push:
    branches: [main]
  pull_request:

jobs:
  testbenches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: YosysHQ/setup-oss-cad-suite@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.OSS_CAD_SUITE }}
      - name: sync_fifo
        run: make MOD=sync_fifo
      - name: synchronizer
        run: make MOD=synchronizer
      - name: async_fifo
        run: make MOD=async_fifo

  formal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: YosysHQ/setup-oss-cad-suite@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.OSS_CAD_SUITE }}
      - name: async_fifo formal
        run: make formal MOD=async_fifo
