name: CI

on: [push, pull_request]

jobs:
  testbenches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog
      - name: sync_fifo
        run: make MOD=sync_fifo
